joshuaslate/type-cacheable

- package.json
Upticking and releasing a new version on npm that contains the ability to dynamically set TTL.
> Releasing 0.1.9

- lib/adapters/RedisAdapter.ts
- lib/decorators/CacheClear.ts
- lib/decorators/Cacheable.ts
- lib/util/getCacheKey.ts
- lib/util/index.ts
- package.json
- test/adapters/RedisAdapter.test.ts
- yarn.lock
> fix: using hmset properly in redis and updating packages

- README.md
- lib/adapters/NodeCacheAdapter.ts
- lib/adapters/RedisAdapter.ts
- lib/decorators/CacheClear.ts
- lib/interfaces/CacheClearOptions.ts
- lib/interfaces/CacheClient.ts
- package.json
- yarn.lock
The purpose of this PR is to allow multiple matched keys to be removed from the cache
> added isPattern parameter to ClearCache to remove matched keys from cache

- README.md
- lib/adapters/IoRedisAdapter.ts
- lib/adapters/index.ts
- lib/util/index.ts
- lib/util/useAdapter.ts
- package.json
- test/adapters/IoRedisAdapter.test.ts
adapter was covered with related tests, documentation and dependencies.
Also, it related to issue #98 which fixed for ioredis adapter in this PR.
> add ioredis adapter

- lib/adapters/NodeCacheAdapter.ts
This should fix #103. Basically, I forgot to return early, so the cache was being set with an expiration, then set again without. 🙈
> fix: ttl not being respected on set for node-cache (#103)

- README.md
- lib/adapters/RedisAdapter.ts
- lib/util/getCacheKey.ts
- lib/util/parseIfRequired.ts
- package.json
- test/adapters/RedisAdapter.test.ts
- yarn.lock
This should, in theory, fix #98.
> Fix for #98

- lib/adapters/RedisAdapter.ts
- lib/decorators/Cacheable.ts
I added boolean transformation support to RedisAdapter, fixed scalar numbers not being transformed properly, and added a fix for a false cache miss scenario when cacheValue is not null but evaluates to false
> Boolean support, scalar number fix, false cache miss fix

- package.json
This adds the ability to install the module directly from github too
> Add prepare script to package.json

- lib/decorators/CacheClear.ts
- lib/decorators/Cacheable.ts
- package.json
- yarn.lock
> fix: #136, moving no-op up

- README.md
- packages/core/lib/CacheManager.ts
- packages/core/lib/decorators/CacheClear.ts
- packages/core/lib/decorators/Cacheable.ts
- packages/core/lib/interfaces/CacheClearOptions.ts
- packages/core/lib/interfaces/CacheOptions.ts
- packages/core/lib/interfaces/CacheStrategyContext.ts
- packages/core/lib/strategies/DefaultStrategy.ts
- packages/ioredis-adapter/lib/index.ts
- packages/ioredis-adapter/test/IoRedisAdapter.test.ts
- packages/node-cache-adapter/lib/index.ts
- packages/node-cache-adapter/test/NodeCacheAdapter.test.ts
- packages/redis-adapter/lib/index.ts
- packages/redis-adapter/test/RedisAdapter.test.ts
As per #198, this adds the option for a fallback cache.
> feat: #198 - adding fallbackCache

- README.md
- packages/ioredis-adapter/README.md
- packages/lru-cache-adapter/README.md
- packages/lru-cache-adapter/jest.config.js
- packages/lru-cache-adapter/lib/index.ts
- packages/lru-cache-adapter/package.json
- packages/lru-cache-adapter/test/LRUCacheAdapter.test.ts
- packages/lru-cache-adapter/tsconfig.json
- packages/node-cache-adapter/README.md
- packages/node-cache-adapter/lib/index.ts
- packages/redis-adapter/README.md
- yarn.lock
This adds a new adapter for those interested in using lru-cache.
> feat: add lru-cache adapter

- packages/core/lib/decorators/CacheClear.ts
- packages/core/lib/strategies/DefaultClearStrategy.ts
- packages/core/lib/strategies/DefaultStrategy.ts
- packages/core/lib/strategies/DefaultUpdateStrategy.ts
Adding a bit more context to debug logs.
> Enhancing logs

- packages/lru-cache-adapter/lib/index.ts
Updating lru-cache adapter to convert seconds to ms.
> #304 - fix lru ttl seconds -> ms

- packages/core/lib/decorators/CacheClear.ts
- packages/core/test/decorators/CacheClear.test.ts
`@CacheClear` is currently deleting the cache even if the decorated method throws an error, unlike the docs description.
By the way, great project! 🎉
> Bypass cache clear when decorated method throws on @CacheClear decorator

- .travis.yml
- package.json
- packages/core/lib/decorators/CacheClear.ts
- packages/core/lib/decorators/CacheUpdate.ts
- packages/core/lib/decorators/Cacheable.ts
- packages/core/lib/strategies/DefaultStrategy.ts
- packages/core/package.json
- packages/core/test/decorators/CacheClear.test.ts
- packages/core/test/decorators/CacheUpdate.test.ts
- packages/core/test/decorators/Cacheable.test.ts
- packages/core/test/test-utils.ts
- packages/ioredis-adapter/package.json
- packages/ioredis-adapter/test/IoRedisAdapter.test.ts
- packages/lru-cache-adapter/package.json
- packages/node-cache-adapter/package.json
- packages/redis-adapter/package.json
- packages/redis-adapter/test/RedisAdapter.test.ts
- tsconfig.json
- yarn.lock
Limits simultaneous method calls by keeping track of active calls and awaiting their results.
> fix: #444 - limit simultaneous method calls

- packages/ioredis-adapter/package.json
- packages/lru-cache-adapter/package.json
- packages/node-cache-adapter/package.json
- packages/redis-adapter/package.json
- fixing peer dep issue reported in #479 🤦
> fix: #479 - peer dep issue

- package.json
- packages/core/lib/decorators/CacheClear.ts
- packages/core/lib/strategies/DefaultClearStrategy.ts
- packages/core/lib/strategies/DefaultStrategy.ts
- packages/core/lib/strategies/DefaultUpdateStrategy.ts
- packages/core/package.json
- packages/ioredis-adapter/package.json
- packages/lru-cache-adapter/package.json
- packages/node-cache-adapter/package.json
- packages/redis-adapter/package.json
- yarn.lock
Updating TypeScript to latest.
> deps: update typescript to 4.4.3

- package.json
- packages/core/package.json
- packages/ioredis-adapter/lib/index.ts
- packages/ioredis-adapter/package.json
- packages/ioredis-adapter/test/IoRedisAdapter.test.ts
- packages/lru-cache-adapter/package.json
- packages/node-cache-adapter/package.json
- packages/redis-adapter/lib/index.ts
- packages/redis-adapter/package.json
- yarn.lock
update redis libraries and others
> chore: update redis libraries

- packages/ioredis-adapter/lib/index.ts
- packages/ioredis-adapter/package.json
- packages/redis-adapter/lib/index.ts
- packages/redis-adapter/package.json
- yarn.lock
Updating compare-versions & node types.
> chore: update deps

- packages/ioredis-adapter/lib/index.ts
- packages/ioredis-adapter/package.json
ioredis-adapter support to search with patterns in a Redis Cluster environment [808](https://github.com/joshuaslate/type-cacheable/issues/808)
> [808] feat: ioredis key scan on Redis Cluster 

- README.md
- packages/core/lib/decorators/CacheUpdate.ts
- packages/core/lib/interfaces/CacheUpdateOptions.ts
- fix: [BREAKING] - cacheKeysToClear default behavior of clearing values, made nullable
> fix: cacheKeysToClear default behavior of clearing values, made nullable

- packages/core/lib/decorators/CacheClear.ts
- packages/core/lib/decorators/CacheUpdate.ts
- packages/core/lib/decorators/Cacheable.ts
- packages/core/lib/index.ts
- packages/core/lib/util/index.ts
- packages/core/lib/util/setMetadata.ts
- packages/core/package.json
- packages/ioredis-adapter/package.json
- packages/lru-cache-adapter/package.json
- packages/node-cache-adapter/package.json
- packages/redis-adapter/package.json
- yarn.lock
> Implemented propagating of other decorators metadata

- README.md
- packages/core/lib/decorators/Cacheable.ts
- packages/core/lib/interfaces/CacheOptions.ts
- packages/core/lib/interfaces/CacheStrategyContext.ts
- packages/core/lib/interfaces/IsCacheable.ts
- packages/core/lib/interfaces/IsCacheableBuilder.ts
- packages/core/lib/interfaces/index.ts
- packages/core/lib/strategies/DefaultStrategy.ts
- packages/core/lib/util/getCacheUpdateStrategy.ts
- packages/core/test/decorators/Cacheable.test.ts
> feat: Introduce isCachable for conditional caching

- packages/core/lib/strategies/DefaultStrategy.ts
> fix: return early from error to prevent SET from being called

- packages/ioredis-adapter/package.json
- packages/lru-cache-adapter/package.json
- packages/node-cache-adapter/package.json
- packages/redis-adapter/package.json
> fix: peer deps

- README.md
- packages/core/lib/strategies/NoOpStrategy.ts
- packages/core/lib/strategies/index.ts
- packages/core/lib/util/getCacheKey.ts
- packages/core/package.json
- packages/core/tsconfig.json
- packages/ioredis-adapter/README.md
- packages/ioredis-adapter/lib/index.ts
- packages/ioredis-adapter/tsconfig.json
- packages/lru-cache-adapter/lib/index.ts
- packages/lru-cache-adapter/test/LRUCacheAdapter.test.ts
- packages/lru-cache-adapter/tsconfig.json
- packages/node-cache-adapter/README.md
- packages/node-cache-adapter/lib/index.ts
- packages/node-cache-adapter/test/NodeCacheAdapter.test.ts
- packages/node-cache-adapter/tsconfig.json
- packages/redis-adapter/README.md
- packages/redis-adapter/lib/index.ts
- packages/redis-adapter/tsconfig.json
- yarn.lock
> replace node crypto with blueimp-md5 for browser compat
